services:
  - type: web
    name: ai-code-review
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: app-instance
      mountPath: /opt/render/project/src/instance
      sizeGB: 1